/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  Kryptos                                */
/*      FILE         :  Kryptos.c                              */
/*      DESCRIPTION  :  Main Program                           */
/*      CPU SERIES   :  RX600                                  */
/*      CPU TYPE     :  RX631                                  */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/

#include <stdint.h>
#include "my_typedef.h"
#include "iodefine.h"
#include "app.h"
#include "run.h"
#include "init.h"
#include "intrpt.h"
#include "serial.h"
#include "sensor.h"
#include "global.h"
#include "common.h"
#include "parameter.h"
#include "map.h"

void main(void) {
	init();
	checkBatt();

	switch (selectMode(10)) {
	case 0: //////////////////////////////////////////////////////////////////////////////////////
		driveRGB(RED, ON);
		driveMotor(ON);
		switchSensorLED(ON);
		waitTime(5000);
		calcGyroZRef();
		g_test_flag = 1;
		g_log_count = 0;
		g_distance = 0;

		searchAdachi();
		switchSensorLED(ON);
		driveMotor(OFF);
		waitButton();
		printLog();
		break;
	case 1: //////////////////////////////////////////////////////////////////////////////////////
		driveRGB(GREEN, ON);
		driveMotor(ON);
		waitTime(2000);
		calcGyroZRef();
		g_test_flag = 1;
		g_log_count = 0;
		g_distance = 0;
		runStraight(5, 0.03 + SECTION + SECTION * 13 + 0.03, 1.3, 1.0);

		turnCorner(turn_90_wide_R);

		runStraight(5, SECTION * 13 + 0.06 + 0.03, 1.3, 1.0);

		turnCorner(turn_90_wide_R);

		runStraight(5, SECTION * 13 + 0.06 + 0.03, 1.3, 1.0);

		turnCorner(turn_90_wide_R);

		runStraight(5, SECTION * 13 + 0.06 + 0.03, 1.3, 1.0);

		turnCorner(turn_90_wide_R);

		runStraight(5, SECTION * 13 + 0.06 + 0.03, 1.3, 1.0);

		turnCorner(turn_90_wide_R);

		runStraight(5, SECTION * 13 + 0.06 + 0.03, 1.3, 1.0);

		turnCorner(turn_90_wide_R);

		runStraight(5, SECTION * 13 + 0.06 + 0.03, 1.3, 1.0);

		turnCorner(turn_90_wide_R);

		runStraight(5, SECTION * 13 + 0.06 + 0.03, 1.3, 1.0);

		turnCorner(turn_90_wide_R);

		runStraight(5, HALF_SECTION * 3 + 0.06, 1.3, 0);

		waitTime(1000);
		driveMotor(OFF);
		waitButton();
		printLog();
		break;
	case 2: //////////////////////////////////////////////////////////////////////////////////////
		driveRGB(BLUE, ON);

		waitTime(3000);
		driveRGB(GREEN, ON);
		calcGyroZRef();

		while (1) {

			myprintf("%f %f\n", g_current_angularvelo, g_angle);
		}
		break;
	case 3: //////////////////////////////////////////////////////////////////////////////////////
		driveRGB(YELLOW, ON);
		switchSensorLED(ON);
		driveMotor(ON);
		waitTime(2000);
		calcGyroZRef();

		g_test_flag = 1;
		g_log_count = 0;
		g_distance = 0;
		runStraight(5, SECTION * 2 + HALF_SECTION, 1.3, 0.5);

		turnCorner(turn_90_R);

		runStraight(5, SECTION * 2 + HALF_SECTION, 1.3, 0);
		switchSensorLED(ON);
		driveMotor(OFF);
		waitButton();
		printLog();
		break;
	case 4: //////////////////////////////////////////////////////////////////////////////////////
		driveRGB(CYAN, ON);

		break;
	case 5: //////////////////////////////////////////////////////////////////////////////////////
		driveRGB(MAGENTA, ON);
		driveMotor(ON);
		switchSensorLED(ON);
		waitTime(2000);
		calcGyroZRef();
		g_test_flag = 1;
		g_log_count = 0;
		g_distance = 0;
		runStraight(5, SECTION * 5, 3, 0);
		waitTime(1000);
		driveMotor(OFF);
		waitButton();
		printLog();
		break;
	case 6: //////////////////////////////////////////////////////////////////////////////////////
		driveRGB(WHITE, ON);

		break;
	case 7: //////////////////////////////////////////////////////////////////////////////////////
		driveRGB(ORANGE, ON);

		break;
	case 8: //////////////////////////////////////////////////////////////////////////////////////
		driveRGB(WATER, ON);
		switchSensorLED(ON);
		while (1) {

			myprintf("FL:%6.1d L:%6.1d R:%6.1d FR:%6.1d\n", g_sensor_FL,
					g_sensor_L, g_sensor_R, g_sensor_FR);
			waitTime(50);
		}
		break;
	case 9: //////////////////////////////////////////////////////////////////////////////////////
		driveRGB(LBLUE, ON);
		driveSuction(100, ON);
		break;
	case 10: //////////////////////////////////////////////////////////////////////////////////////
		driveRGB(LRED, ON);
		calcGyroZRef();
		g_test_flag = 1;

		setMotorDirL(FORWARD);
		setMotorDirR(FORWARD);

		driveMotor(ON);
		while (1) {

		}
		break;
	default: //////////////////////////////////////////////////////////////////////////////////////
		break;
	}

}
