/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  Kryptos                                */
/*      FILE         :  Kryptos.c                              */
/*      DESCRIPTION  :  Main Program                           */
/*      CPU SERIES   :  RX600                                  */
/*      CPU TYPE     :  RX631                                  */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/

#include <stdint.h>
#include "my_typedef.h"
#include "iodefine.h"
#include "app.h"
#include "run.h"
#include "init.h"
#include "intrpt.h"
#include "serial.h"
#include "sensor.h"
#include "global.h"
#include "common.h"
#include "parameter.h"
#include "map.h"
#include "contest.h"

void main(void) {
	init();
	checkBatt();

	switch (selectMode(10)) {
	case 0: //////////////////////////////////////////////////////////////////////////////////////
		driveRGB(ORANGE, ON);
		waitSensor();

		driveRGB(CYAN, ON);
		switchSensorLED(ON);
		driveMotor(ON);
		soundStart();
		calcGyroZRef();
		g_flag_control = 1;
		g_log_count = 0;
		g_distance = 0;

		searchAdachi();
		switchSensorLED(OFF);
		driveMotor(OFF);
		g_current_x = START_X;
		g_current_y = START_Y;
		g_orient = 0x01;
		countStepShortest();
		makePath();
		makePath2();
		makePath3();

		driveRGB(BLUE, ON);
		waitButton();

		waitSensor();
		switchSensorLED(ON);
		soundNotification();
		driveRGB(GREEN, ON);
		waitTime(1000);
		calcGyroZRef();
		soundStart();
		driveSuction(70, OFF);
		waitTime(1000);
		g_flag_control = 1;
		g_log_count = 0;
		g_distance = 0;
		g_target_velo = 0;
		driveMotor(ON);
		runPathDiagonal();
		switchSensorLED(ON);
		driveMotor(OFF);
		driveSuction(100, OFF);

		waitButton();
		 printLog();
		break;
	case 1: //////////////////////////////////////////////////////////////////////////////////////
		driveRGB(MAGENTA, ON);
		waitButton();

		waitSensor();

		soundNotification();
		driveRGB(GREEN, ON);
		waitTime(1000);
		g_flag_control = 1;
		g_log_count = 0;
		g_distance = 0;
		g_target_velo = 0;
		driveMotor(ON);
		runStraight(5, HALF_SECTION, 0.5, 0.5);
		while (1) {

			runStraight(5, SECTION, 0.5, 0.5);
			turnCorner(turn_90_L);
		}
		break;
	case 2: //////////////////////////////////////////////////////////////////////////////////////
		driveRGB(BLUE, ON);

		waitButton();

		waitSensor();

		soundNotification();
		driveRGB(GREEN, ON);
		waitTime(1000);
		g_flag_control = 1;
		g_log_count = 0;
		g_distance = 0;
		g_target_velo = 0;
		driveMotor(ON);
		runStraight(5, HALF_SECTION, 0.5, 0.5);
		while (1) {

			runStraight(5, SECTION, 0.5, 0.5);
			turnCorner(turn_90_R);
		}

		break;
	case 3: //////////////////////////////////////////////////////////////////////////////////////
		driveRGB(YELLOW, ON);

		waitButton();

		waitSensor();

		soundNotification();
		driveRGB(GREEN, ON);
		waitTime(1000);
		g_flag_control = 1;
		g_log_count = 0;
		g_distance = 0;
		g_target_velo = 0;
		driveMotor(ON);

		runStraight(5, SECTION, 0.5, 0.5);
		turnCorner(turn_90_L);
		runStraight(5, SECTION, 0.5, 0);

		break;
	case 4: //////////////////////////////////////////////////////////////////////////////////////
		driveRGB(CYAN, ON);

		waitButton();

		waitSensor();

		soundNotification();
		driveRGB(GREEN, ON);
		waitTime(1000);
		g_flag_control = 1;
		g_log_count = 0;
		g_distance = 0;
		g_target_velo = 0;
		driveMotor(ON);

		runStraight(5, SECTION, 0.5, 0.5);
		turnCorner(turn_90_R);
		runStraight(5, SECTION, 0.5, 0);
		break;
	case 5: //////////////////////////////////////////////////////////////////////////////////////
		driveRGB(MAGENTA, ON);
		waitButton();

		waitSensor();
		//switchSensorLED(OFF);
		soundNotification();
		driveRGB(GREEN, ON);
		waitTime(1000);
		g_flag_control = 1;
		g_log_count = 0;
		g_distance = 0;
		g_target_velo = 0;
		driveMotor(ON);
		runStraight(5, SECTION, 0.5, 0.5);
		runBlindAlley(0.5);
		runStraight(5, SECTION, 0.5, 0);
		break;
	case 6: //////////////////////////////////////////////////////////////////////////////////////
		driveRGB(WHITE, ON);

		waitButton();

		waitSensor();

		soundNotification();
		driveRGB(GREEN, ON);
		waitTime(1000);
		g_flag_control = 1;
		g_log_count = 0;
		g_distance = 0;
		g_target_velo = 0;
		driveMotor(ON);

		while (1) {
			turnCorner(pivot);
			waitTime(200);
		}

		break;
	case 7: //////////////////////////////////////////////////////////////////////////////////////
		driveRGB(ORANGE, ON);

		break;
	case 8: //////////////////////////////////////////////////////////////////////////////////////
		driveRGB(WATER, ON);
		switchSensorLED(ON);
		while (1) {

			myprintf("FL:%6.1d L:%6.1d R:%6.1d FR:%6.1d\n", g_sensor_FL,
					g_sensor_L, g_sensor_R, g_sensor_FR);
			waitTime(50);
		}
		break;
	case 9: //////////////////////////////////////////////////////////////////////////////////////
		driveRGB(LBLUE, ON);
		driveSuction(100, ON);
		break;
	case 10: //////////////////////////////////////////////////////////////////////////////////////
		driveRGB(LRED, ON);
		waitSensor();
		soundNotification();
		calcGyroZRef();
		switchSensorLED(ON);
		g_flag_control = 1;
		g_flag_blindalley=1;
		driveMotor(ON);
		while (1) {

		}
		break;
	default: //////////////////////////////////////////////////////////////////////////////////////
		break;
	}

}

/*


 while (1) {
 myprintf("%f\n", returnGyroZVal());
 waitTime(50);
 }





 switchSensorLED(ON);
 waitSensor();
 soundStart();
 g_flag_control = 1;
 g_log_count = 0;
 g_distance = 0;
 calcGyroZRef();

 driveMotor(ON);

 runStraight(5, SECTION, 1.3, 1);

 turnCorner(turn_180_R_1000);

 runStraight(5, SECTION, 1.3, 0);
 switchSensorLED(ON);
 driveMotor(OFF);
 waitButton();
 printLog();





 waitTime(3000);
 driveRGB(GREEN, ON);
 calcGyroZRef();

 while (1) {

 myprintf("%f %f\n", g_current_angularvelo, g_angle);

 }

 */
