/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  Kryptos                                */
/*      FILE         :  sbrk.h                                 */
/*      DESCRIPTION  :  Header file of sbrk file               */
/*      CPU SERIES   :  RX600                                  */
/*      CPU TYPE     :  RX631                                  */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/

/* size of area managed by sbrk */
#define HEAPSIZE 0x400